# CLI: https://docs.docker.com/engine/reference/commandline/compose_exec/#related-commands
# Compose file versions: https://docs.docker.com/compose/compose-file/compose-versioning/
version: '3'
services:
  db:
    container_name: chatbot_sdk-pgvector
    image: ankane/pgvector
    restart: always
    ports:
      - 5432:5432
    networks:
      - chatbot_sdk-network
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      # - ./tmp/pg_data:/var/lib/postgresql/data
      - ./tmp/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: chatbot_sdk-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - chatbot_sdk-network
    command: redis-server --appendonly yes
    volumes:
      - ./tmp/redis_data:/data
networks:
  chatbot_sdk-network:
